export default [
  {
    placeName: "Dharamshala",
    placeState: "Himachal Pradesh",
    placeCountry: "India",
    language: "Hindi",
    images: [
      "images/india/himachal/dharamshala/1.jpg",
      "images/india/himachal/dharamshala/2.jpg",
      "images/india/himachal/dharamshala/3.jpg",
      "images/india/himachal/dharamshala/4.jpg",
      "images/india/himachal/dharamshala/5.jpeg",
    ],
    description:
      "Dharamshala is the winter capital of Himachal Pradesh. This place is also famous for its Himachal Pradesh Cricket Association Stadium (2003), which offers opportunities to the youth of state to prepare for their future in the game. The McLeod Ganj town, lying in the upper reaches, is known worldwide for the presence of the Dalai Lama. On 29 April 1959, the 14th Dalai Lama (Tenzin Gyatso) established the Tibetan exile administration in the north Indian hill station of Mussoorie. In May 1960, the Central Tibetan Administration (CTA) was moved to Dharamshala, making it the centre of the Tibetan exile world in India.",
    coords: [32.219044, 76.323402],
  },
  {
    placeName: "Lahaul Spiti",
    placeState: "Himachal pradesh",
    placeCountry: "India",
    language: "Spiti bhoti",
    images: [
      "images/india/himachal/spiti/1.jpg",
      "images/india/himachal/spiti/2.jpg",
      "images/india/himachal/spiti/3.jpg",
      "images/india/himachal/spiti/4.jpg",
      "images/india/himachal/spiti/5.jpg",
      "images/india/himachal/spiti/6.jpg",
    ],
    description:
      "The Lahaul and Spiti district in the Indian state of Himachal Pradesh consists of the two formerly separate districts of Lahaul and Spiti. The natural scenery and numerous Buddhist monasteries are the main tourist attractions of the region. The dangerous weather in Lahaul and Spiti permits visitors to tour only between the months of June to October, when the roads and villages are free of snow and the high passes (Rothang La and Kunzum La) are open. It is possible to access Spiti from Kinnaur (along the Sutlej) all through the year, although the road is sometimes temporarily closed by landslides or avalanches. Spiti is one of the important centers of Buddhism in Himachal Pradesh. It is popularly known as the 'land of lamas'. The valley is dotted by numerous Buddhist Monasteries or Gompas.",
    coords: [32.6192, 77.3784],
  },
  {
    placeName: "Leh",
    placeState: "Ladakh",
    placeCountry: "India",
    language: "Ladakhi",
    images: [
      "images/india/leh/1.jpg",
      "images/india/leh/2.jpg",
      "images/india/leh/3.jpg",
      "images/india/leh/4.jpg",
      "images/india/leh/5.jpg",
      "images/india/leh/6.jpg",
      "images/india/leh/7.jpg",
    ],
    description:
      "Leh is the joint capital and largest city of the region administered by India as a union territory of Ladakh. Leh, located in the Leh district, was also the historical capital of the Kingdom of Ladakh, the seat of which was in the Leh Palace, the former residence of the royal family of Ladakh, built in the same style and about the same time as the Potala Palace in Tibet. Leh is connected to the rest of India by two high-altitude roads both of which are subject to landslides and neither of which are passable in winter when covered by deep snows. The National Highway 1 from Srinagar via Kargil is generally open longer. The Leh-Manali Highway can be troublesome due to very high passes and plateaus.",
    coords: [34.152588, 77.577049],
  },
  {
    placeName: "Chamba",
    placeState: "Himachal Pradesh",
    placeCountry: "India",
    language: "Chambiyali",
    images: [
      "images/india/himachal/chamba/1.jpg",
      "images/india/himachal/chamba/2.jpg",
      "images/india/himachal/chamba/3.jpg",
      "images/india/himachal/chamba/4.jpg",
      "images/india/himachal/chamba/5.jpg",
      "images/india/himachal/chamba/6.jpg",
    ],
    description:
      'Chamba is the northernmost district of Himachal Pradesh, and lies at the intersection of Dhauladhar and Zanskar ranges. These are facts related to this district, but aren’t particularly interesting. What is interesting is the opening lines of a famous Himachali folk song which go like this - Shimla nahi basna, Kasauli nahi basna, Chamba jana zaroor. When translated, they mean - Don’t settle in Shimla, don’t settle in Kasauli, but certainly visit Chamba. It is only when you spend your holidays in Chamba that you realise the significance of the song. The landscape here is marked by lakes, streams, meadows, alpine tree covers, valleys and rich wildlife. There are historical attractions, and architectural ones. The main town is located on the banks of the River Ravi, and is surrounded by mountains with dense forests. There are numerous opportunities for sightseeing, thanks to its illustrious past. It is the culture of Chamba though, that leaves you fascinated. The rich artistic heritage of the city is reflected in its miniature paintings, temple architecture and the famous "Chamba Rumal".',
    coords: [32.5534, 76.1258],
  },
  {
    placeName: "Manali",
    placeState: "Himachal Pradesh",
    placeCountry: "India",
    language: "Western Pahari",
    images: [
      "images/india/himachal/manali/1.png",
      "images/india/himachal/manali/2.jpg",
      "images/india/himachal/manali/3.jpg",
      "images/india/himachal/manali/4.jpeg",
      "images/india/himachal/manali/5.jpg",
      "images/india/himachal/manali/6.jpg",
      "images/india/himachal/manali/7.jpeg",
    ],
    description:
      "One of the most popular hill stations in Himachal, Manali offers the most magnificent views of the Pir Panjal and the Dhauladhar ranges covered with snow for most parts of the year. Manali has many trekking options around it, making it a great base for exploring this side of Himalayas. River Beas provides great rafting options in the nearby town of Kullu. Adjoining Parvati river, lies the Parvati Valley with  Kasol, Manikaran, Tosh and small villages attracting travellers for longer stays. Atal Tunnel now allows travellers to reach Sissu within a few hours making Spiti way more accessible. Tourists flock to Rohtang Pass & Solang valley for various adventure activities including skiing, paragliding, horse-riding & zorbing. Rohtang Pass is almost always covered with snow and can often get overcrowded and see traffic jams.",
    coords: [32.2432, 77.1892],
  },
  {
    placeName: "Nainital",
    placeState: "Uttrakhand",
    placeCountry: "India",
    language: "	Kumaoni",
    images: [
      "images/india/nainital/1.jpg",
      "images/india/nainital/2.jpeg",
      "images/india/nainital/3.jpg",
    ],
    description:
      "Nainital is a charming hill station located at the foothills of the Kumaon ranges in Uttarakhand. Located close to Dehradun and Delhi, it is the most visited hill station in North India. Nainital is a perfect weekend getaway from Delhi and the nearby places. Nainital experiences a pleasant climate throughout the year, making it a popular hill station for families, couples and even solo travellers. It is easily accessible from nearby major cities by road and is ideal for a 2-day visit. The Naina Lake is the centre of Nainital with Mall Road on one side, Thandi Sadak on the other side, and the bus stand opposite it. ",
    coords: [29.3919, 79.4542],
  },
  {
    placeName: "Mussoorie",
    placeState: "Uttrakhand",
    placeCountry: "India",
    language: "	Garhwali",
    images: [
      "images/india/mussoorie/1.jpg",
      "images/india/mussoorie/2.jpg",
      "images/india/mussoorie/3.jpg",
      "images/india/mussoorie/4.jpg",
    ],
    description:
      "Mussoorie, also known as Queen of the Hills, is among the most popular hill stations of the country. A Britisher, Captain Frederick Young, accompanied by an official named FJ Shore, had climbed up the hill from the Doon valley in 1827 and found this ridge offering great views and a salubrious climate. This visit laid the foundation for this grand hill station. A captivating paradise for leisure travellers and honeymooners, it is a perfect summer resort. Located on a 15-km-long horseshoe ridge with the grand Himalayas as a backdrop, Mussoorie spreads across at a height of 2,000 m above sea level. From this vantage point, it offers scenic views of Himalayas peaks in Western Garhwal. ",
    coords: [30.459909, 78.066399],
  },
  {
    placeName: "Banff",
    placeState: "Alberta",
    placeCountry: "Canada",
    language: "	English",
    images: [
      "images/canada/banff/1.jpg",
      "images/canada/banff/2.jpg",
      "images/canada/banff/3.jpg",
      "images/canada/banff/4.jpg",
      "images/canada/banff/5.jpg",
      "images/canada/banff/6.jpg",
      "images/canada/banff/7.jpg",
    ],
    description:
      "Banff is a resort town in the province of Alberta, located within Banff National Park. The peaks of Mt. Rundle and Mt. Cascade, part of the Rocky Mountains, dominate its skyline. On Banff Avenue, the main thoroughfare, boutiques and restaurants mix with château-style hotels and souvenir shops. The surrounding 6,500 square kilometres of parkland are home to wildlife including elk and grizzly bears.",
    coords: [51.1784, -115.5708],
  },
  {
    placeName: "Tobermory",
    placeState: "Ontario",
    placeCountry: "Canada",
    language: "	English",
    images: [
      "images/canada/tobermory/1.jpg",
      "images/canada/tobermory/2.jpg",
      "images/canada/tobermory/3.jpg",
      "images/canada/tobermory/4.jpg",
      "images/canada/tobermory/5.jpg",
      "images/canada/tobermory/6.jpg",
    ],
    description:
      "Tobermory, Ontario is a breathtaking vacation spot found at the northern tip of the Bruce Peninsula. Home to Fathom Five National Marine Park and the final resting place of some two dozen shipwrecks that make Tobermory the scuba diving centre of the Great Lakes. An adventurer's paradise, hikers will enjoy the world-famous 700-kilometre Bruce Trail. Nearby is the Bruce Peninsula National Park Visitors' Centre with its tall lookout tower and interpretive exhibits. Visitors can ride the Chi-Cheemaun across the Devil's Gap to Manitoulin Island, speed across the crystal clear waters on a zodiak,explore the wonders of Flowerpot Island, and view old shipwrecks from a glass bottom boat.Stroll through quaint shops, art galleries, ship chandlers, and a wonderful array of pubs and restaurants serving fresh, locally caught whitefish.",
    coords: [45.2534, -81.6645],
  },
  {
    placeName: "Blue Mountains",
    placeState: "Ontario",
    placeCountry: "Canada",
    language: "	English",
    images: [
      "images/canada/blue/1.jpg",
      "images/canada/blue/2.jpg",
      "images/canada/blue/3.jpg",
      "images/canada/blue/4.jpg",
      "images/canada/blue/5.jpg",
      "images/canada/blue/6.jpg",
      "images/canada/blue/7.jpg",
      "images/canada/blue/8.jpg",
    ],
    description:
      "Blue Mountain is an alpine ski resort in Ontario, Canada, just northwest of Collingwood. It is situated on a section of the Niagara Escarpment about 1 km (0.6 mi.) from Nottawasaga Bay, and is a major destination for skiers from southern Ontario. The local area forms the newly incorporated town of The Blue Mountains, Ontario. On average, Blue Mountain sells more than 750,000 lift tickets per year, making it the third-busiest ski resort in Canada, after Whistler-Blackcomb in British Columbia and Mont Tremblant in Quebec. It is one of the largest resorts in Ontario and has been extensively built out, featuring 42 runs, 16 chairlifts and 3 freestyle terrains.",
    coords: [44.5038, -80.3122],
  },
  {
    placeName: "Niagara Falls",
    placeState: "Ontario",
    placeCountry: "Canada",
    language: "	English",
    images: [
      "images/canada/niagara/1.jpg",
      "images/canada/niagara/2.jpg",
      "images/canada/niagara/3.jpg",
      "images/canada/niagara/4.jpg",
      "images/canada/niagara/5.jpg",
    ],
    description:
      "Niagara Falls, Ontario, is a Canadian city at the famous waterfalls of the same name, linked with the U.S. by the Rainbow Bridge. Its site on the Niagara River's western shore overlooks the Horseshoe Falls, the cascades' most expansive section. Elevators take visitors to a lower, wetter vantage point behind the falls. A cliffside park features a promenade alongside 520-ft.-high Skylon Tower with an observation deck.",
    coords: [43.0896, -79.0849],
  },
  {
    placeName: "Toronto",
    placeState: "Ontario",
    placeCountry: "Canada",
    language: "	English",
    images: [
      "images/canada/toronto/1.jpg",
      "images/canada/toronto/2.jpg",
      "images/canada/toronto/3.jpg",
      "images/canada/toronto/4.jpg",
      "images/canada/toronto/5.jpg",
    ],
    description:
      "Toronto, the capital of the province of Ontario, is a major Canadian city along Lake Ontario’s northwestern shore. It's a dynamic metropolis with a core of soaring skyscrapers, all dwarfed by the iconic, free-standing CN Tower. Toronto also has many green spaces, from the orderly oval of Queen’s Park to 400-acre High Park and its trails, sports facilities and zoo.",
    coords: [43.6532, -79.3832],
  },
];
